### PR TITLE
PaRe Report as article

### PR DESCRIPTION
**Pull request by mvankessel-EMC**
I've added the Report.Rmd file to `./vignettes/articles/`. Feel free to alter Report.Rmd for future releases.

### CODE REVIEW

**Comment by edward-burn** [comment]
Thanks @mvankessel-EMC, could you please take a look at why the pkdown action is failing? https://github.com/oxford-pharmacoepi/PatientProfiles/actions/runs/4991961467/jobs/8949993650?pr=240

It seems to be complaining that it can't install PaRe, but I thought the benefit of an article was that it wouldn't try and rebuild in rmd output so I'm not sure why that's occuring.

**Comment by mvankessel-EMC** [comment]
> Thanks @mvankessel-EMC, could you please take a look at why the pkdown action is failing? https://github.com/oxford-pharmacoepi/PatientProfiles/actions/runs/4991961467/jobs/8949993650?pr=240
> 
> It seems to be complaining that it can't install PaRe, but I thought the benefit of an article was that it wouldn't try and rebuild in rmd output so I'm not sure why that's occuring.

When building the site through Github Actions it does so in a clean environment, I did not list PaRe is a suggested package (yet). That's why it fails.

It's up to you guys what you like. I can definitely understand not pushing this change before PaRe is on CRAN.

**Comment by edward-burn** [comment]
Oh ok, let's wait until PaRe is on CRAN and then we can add it to suggests and include the article. Maybe it would also be nice to also add something in the contributing guide https://github.com/oxford-pharmacoepi/PatientProfiles/blob/main/.github/CONTRIBUTING.md about generating and using the report?

While you work on getting PaRe on cran we can work on tidying up our code :)

**Comment by mvankessel-EMC** [comment]
> Oh ok, let's wait until PaRe is on CRAN and then we can add it to suggests and include the article. Maybe it would also be nice to also add something in the contributing guide https://github.com/oxford-pharmacoepi/PatientProfiles/blob/main/.github/CONTRIBUTING.md about generating and using the report?

> While you work on getting PaRe on cran we can work on tidying up our code :)

Will do, I'll close this PR for now.

**Pull request closed without merging**
